import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { renderEntry } from "../packages/cli/dist/index.js";
import { migrateMarkdown } from "../packages/migrate/dist/index.js";

const smokeRoot = new URL("../.tmp/", import.meta.url);
await mkdir(smokeRoot, { recursive: true });
const directory = await mkdtemp(join(smokeRoot.pathname, "jsx2md-smoke-"));
const entry = join(directory, "entry.tsx");
const props = { title: "Smoke" };

await writeFile(
  entry,
  [
    "/** @jsxImportSource jsx2md */",
    "/** @jsxRuntime automatic */",
    'import { Doc } from "jsx2md";',
    "export default (props: { title: string }) => (",
    "  <Doc>",
    "    <h1>{props.title}</h1>",
    "    <p>Generated by smoke test.</p>",
    "  </Doc>",
    ");",
  ].join("\n"),
);

const markdown = await renderEntry(entry, { adapter: "github", props });
if (markdown !== "# Smoke\n\nGenerated by smoke test.\n") {
  throw new Error(`Unexpected smoke output: ${JSON.stringify(markdown)}`);
}

const migrated = migrateMarkdown("# Migrated\n\n- [x] Done\n", {
  adapter: "github",
});
if (!migrated.code.includes("<TaskList>")) {
  throw new Error("Migration smoke test did not generate a TaskList.");
}

await readFile(entry, "utf8");
console.log("Smoke tests passed.");
