import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { migrateMarkdown } from "@jsx2md/migrate";
import { renderEntry } from "@jsx2md/cli";

const smokeRoot = new URL("../.tmp/", import.meta.url);
await mkdir(smokeRoot, { recursive: true });
const directory = await mkdtemp(join(smokeRoot.pathname, "jsx2md-smoke-"));
const entry = join(directory, "entry.tsx");
const unsupportedEntry = join(directory, "unsupported.tsx");
const props = { title: "Smoke" };

await writeFile(
  entry,
  [
    "/** @jsxImportSource jsx2md */",
    "/** @jsxRuntime automatic */",
    'import { Doc } from "jsx2md";',
    "export default (props: { title: string }) => (",
    "  <Doc>",
    "    <h1>{props.title}</h1>",
    "    <p>Generated by smoke test.</p>",
    "  </Doc>",
    ");",
  ].join("\n"),
);

await writeFile(
  unsupportedEntry,
  [
    "/** @jsxImportSource jsx2md */",
    "/** @jsxRuntime automatic */",
    'import { Doc } from "jsx2md";',
    "export default (",
    "  <Doc>",
    "    <ul>",
    "      <li checked>Checked</li>",
    "    </ul>",
    "  </Doc>",
    ");",
  ].join("\n"),
);

const markdown = await renderEntry(entry, { adapter: "github", props });
if (markdown !== "# Smoke\n\nGenerated by smoke test.\n") {
  throw new Error(`Unexpected smoke output: ${JSON.stringify(markdown)}`);
}

const fallbackMarkdown = await renderEntry(unsupportedEntry, { unsupported: "plain" });
if (fallbackMarkdown !== "- Checked\n") {
  throw new Error(`Unexpected unsupported fallback output: ${JSON.stringify(fallbackMarkdown)}`);
}

const migrated = migrateMarkdown("# Migrated\n\n- [x] Done\n", {
  adapter: "github",
});
if (!migrated.code.includes('from "@jsx2md/gfm"') || !migrated.code.includes("<TaskList>")) {
  throw new Error("Migration smoke test did not generate GFM task list components.");
}

await readFile(entry, "utf8");
process.stdout.write("Smoke tests passed.\n");
